name: Github Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"

      - uses: actions/checkout@v4.1.2

      - name: List Files
        run: |
          echo "${{github.repository}}" contains:"
          ls -al


        
      
  
      
    
